language: julia
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
script:
- julia -e 'const SOLVER = ENV["SOLVER"]; using Pkg; Pkg.develop("MathOptInterface"); Pkg.add(SOLVER); Pkg.test(SOLVER)'
jobs:
  include:
    - env: SOLVER=Cbc
    - env: SOLVER=CDDLib
    - env: SOLVER=COSMO
    - env: SOLVER=CSDP
    - env: SOLVER=ECOS
    - env: SOLVER=GLPK
    - env: SOLVER=Ipopt
    - env: SOLVER=Juniper
    - env: SOLVER=OSQP
    - env: SOLVER=ProxSDP
    - env: SOLVER=SCS
    - env: SOLVER=SDPA
    - env: SOLVER=Tulip
